# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 656719366d7284b553628d763ee717c99178bf95d203e31dd648cdfa409c5b6cfd3358fe42a0e6618164e512c1a049ff5fb3e879feb424d127bb9657290a1ab3

test:
  secret_key_base: cb303bab6a8b1be4079c45d87c4ab824fef8c485d812480f4cabc2a4bc868907040d880c3a4da03e1a30b182cbb729dd3ae28f0f3b6f38ff849bea799ceccf32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
